header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: coScene

  paths-ignore:
    - '.github/**'
    - '.*'
    - '**/*.md'
    - 'LICENSE'
    - 'Makefile'
    - 'requirements.txt'
    - 'requirements-dev.txt'
    - 'setup.py'
    - 'tox.ini'

  comment: on-failure

# If you don't want to check dependencies' license compatibility, remove the following part
dependency:
  files:
    - requirements.txt
