name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-n-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'
      - name: Install dependencies and api key
        run: |
          pip install -e .[dev]
      - name: Lint with flake8
        run: flake8 src --count --show-source --statistics
      - name: Test with pytest
        run: |
          pytest -p no:logging -p no:warnings
